travis:
  secure:
    BINSTAR_TOKEN: FAZOWmIJfjmoidEiJOpq8AM13JT0bM46YMNPBT+GXCRfaFCOJfeEYQvF5sUY26XUVct6Sq0mr+TeTpwiODvJuNdA/Z0wNMhs879e6uB+muk7/NPROIaTIYwRWuk1u5rGvRPN+YXwIXLSvD3wlXgMXmew4pGVNGOCr2YbFSnHQbMoTNQGKDETuNl6WzAWcVtPECgUjWLS62bCmanMmYx6MG8n3GXheNBkEfj5wll897DqPeXx1U8p74nVwUIjpixfiyM8kEr1RbBYHuxjpJHtRVJIQwjDzUFlwNA/ttkbMRKBLXgJXXnQSYVVT0lYfdD/ySOe2qB3Q3qdgdASMmYwhvn6f4cBX9jucFWrhnnnyn2f1A/hcD+NuKNkhn8vuHwkaSVrg7MxJrKp/T7BvBvakKx9QxZCBMR372HchJMiUdf9lyq9eSZxdZvt7h+lPm7wYnI9duQgzEE7oxcHlocgL/C8fgfXJbZkl+sR5Sa4XLLFKZSonmUjphHfiawKI63vREGBvghzIT1Li0289sU0u5EvWJpmXbCSo1owcLE9CCp6/7ujDxU2iPWV4x08xkfoXJjJOO8TWLZh0NsgKWsZDkDyVFFFfsd1e3AdA8rMx/gdTy1oYeqTgMBU1gBdyRMvy2A+OAmZlQUzhFx7HJ2w6Zav5rdSAmTHXHwkv19KiE8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
